# Generated by Django 3.2.15 on 2022-10-13 08:33

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=29, unique=True)),
                ('slug', models.SlugField(max_length=100, null=True, unique=True)),
                ('label', models.CharField(blank=True, choices=[('aerial', 'Aerial'), ('barre', 'Barre'), ('bootcamp', 'Bootcamp'), ('boxing', 'Boxing'), ('kickboxing', 'Kickboxing'), ('circuit training', 'Circuit training'), ('crossfit', 'Crossfit'), ('cycling', 'Cycling'), ('dance', 'Dance'), ('gym classes', 'Gym classes'), ('interval training', 'Interval training'), ('pilates', 'Pilates'), ('sports', 'Sports'), ('strength training', 'Strength training'), ('yoga', 'Yoga')], max_length=17)),
                ('content', models.TextField()),
                ('featured_image', cloudinary.models.CloudinaryField(blank=True, default='placeholder', max_length=255, verbose_name='image')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_posts', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(blank=True, related_name='forum_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('body', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='forum.post')),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
    ]
