# Generated by Django 3.2.15 on 2022-10-15 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='label',
            field=models.CharField(blank=True, choices=[('healthy eating', 'Healthy Eating'), ('aerial', 'Aerial'), ('barre', 'Barre'), ('bootcamp', 'Bootcamp'), ('boxing', 'Boxing'), ('kickboxing', 'Kickboxing'), ('circuit training', 'Circuit training'), ('crossfit', 'Crossfit'), ('cycling', 'Cycling'), ('dance', 'Dance'), ('gym classes', 'Gym classes'), ('interval training', 'Interval training'), ('pilates', 'Pilates'), ('sports', 'Sports'), ('strength training', 'Strength training'), ('yoga', 'Yoga')], max_length=17),
        ),
    ]
