# Generated by Django 3.2.15 on 2022-08-17 06:45

from django.db import migrations


class Migration(migrations.Migration):
    """..."""

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='excerpt',
        ),
    ]
